steps:

- id: "Gerando service-account-storage.json"
  name: 'gcr.io/cloud-builders/gcloud'
  args: 
    - kms 
    - decrypt 
    - --ciphertext-file=./storage/credentials/google/fc2-projeto-storage.json.enc 
    - --plaintext-file=./storage/credentials/google/fc2-projeto-storage.json 
    - --location=global 
    - --keyring=code-micro-videos 
    - --key=service-account

- id: "Rodando docker-compose"
  name: 'docker/compose'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']
  env: 
    - GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID
    - GOOGLE_CLOUD_KEY_FILE=fc2-projeto-storage.json
    - GOOGLE_CLOUD_STORAGE_BUCKET=ggscode-micro-videos
    - GOOGLE_CLOUD_STORAGE_API_URI=https://storage.cloud.google.com/ggscode-micro-videos
    - TESTING_PROD=true

- id: "Chown in /var/www"
  name: 'docker'
  args: ['exec','-u','root','-t','micro-videos-app','chown','-R','www-data:www-data','/var/www']

- id: "Rodando composer"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'composer', 'install']

- id: "Copiando .env"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'cp', '.env.example', '.env']

- id: "Copiando .env.testing"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'cp', '.env.testing.example', '.env.testing']

- id: "Rodando key:generate"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'key:generate']

- id: "Rodando migration"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'migrate']  

- id: "Rodando PHpunit"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']    