steps:

- id: "Rodando docker-compose"
  name: 'docker/compose'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

- id: "Rodando docker ps"
  name: 'docker'
  args: ['ps']

- id: "Rodando composer"
  name: 'docker'
  args: ['exec', '-t', 'app', 'composer', 'install']  