steps:

- id: "Rodando docker-compose"
  name: 'docker/compose'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

- id: "Rodando composer"
  name: 'docker/compose'
  args: ['exec', 'app', 'composer', 'install']

- id: "Copiando .env"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'cp', '.env.example', '.env']

- id: "Rodando key:generate"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'key:generate']