steps:

- id: "Gerando service-account-storage.json"
  name: 'gcr.io/cloud-builders/gcloud'
  args: 
    - kms 
    - decrypt 
    - --ciphertext-file=./backend/storage/credentials/google/fc2-projeto-storage.json.enc 
    - --plaintext-file=./backend/storage/credentials/google/fc2-projeto-storage.json 
    - --location=global 
    - --keyring=code-micro-videos 
    - --key=service-account

- id: "Rodando docker-compose"
  name: 'docker/compose'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']
  env: 
    - GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID
    - GOOGLE_CLOUD_KEY_FILE=fc2-projeto-storage.json
    - GOOGLE_CLOUD_STORAGE_BUCKET=ggscode-micro-videos
    - GOOGLE_CLOUD_STORAGE_API_URI=https://storage.cloud.google.com/ggscode-micro-videos
    - GOOGLE_CLOUD_STORAGE_PUBLIC_API_URI=https://storage.googleapis.com/ggscode-micro-videos
    - TESTING_PROD=true

- id: "Chown in /var/www"
  name: 'docker'
  args: ['exec','-u','root','-t','micro-videos-app','chown','-R','www-data:www-data','/var/www']

- id: "Rodando composer"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'composer', 'install', '-d', '/var/www/backend']
  
- id: "Copiando .env"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'cp', '/var/www/backend/.env.example', '/var/www/backend/.env']

- id: "Copiando .env.testing"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'cp', '/var/www/backend/.env.testing.example', '/var/www/backend/.env.testing']

- id: "Rodando key:generate"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/backend/artisan', 'key:generate']

- id: "Rodando migration"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/backend/artisan', 'migrate']  

- id: "Rodando PHpunit"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/backend/vendor/bin/phpunit', '-c', '/var/www/backend/phpunit.xml']

- id: "Copiando front-end .env"  
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'cp', '/var/www/frontend/.env.example', '/var/www/frontend/.env']

- id: "Install front-end"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'npm', 'install', '--prefix', '/var/www/frontend']

- id: "Permission on scripts/build.sh"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'chmod', '+x', '/var/www/frontend/scripts/build.sh']

- id: "Build front-end"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'npm', 'run', 'build-laravel', '--prefix', '/var/www/frontend']

- id: "Test laravel and React Integration"
  name: 'docker'
  args: ['exec', '-w', '/var/www/backend', '-t', 'micro-videos-app', 'php', 'artisan', 'dusk', '--env=testing']