### get all
GET http://localhost:8000/api/genres HTTP/1.1

### get genre does not exist
GET http://localhost:8000/api/genres/0 HTTP/1.1
Accept: application/json

### get a specific genre
GET http://localhost:8000/api/genres/f9e13962-50da-4b48-910c-b6c772e92015 HTTP/1.1

### add a new genre
POST http://localhost:8000/api/genres HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "genre 1",
    "is_active": true
}

### add a new genre data invalid
POST http://localhost:8000/api/geners HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "is_active": false
}


### try udpate genre that does not exist
PUT http://localhost:8000/api/genres/0 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "genre update 3"
}

### udpate genre that does not exist
PUT http://localhost:8000/api/genres/52b704b8-bb26-4e67-ae27-ccec93c52f22 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "is_active": false
}

### try delete genre that does not exist
DELETE http://localhost:8000/api/genres/0 HTTP/1.1
Accept: application/json

### delete a genre
DELETE http://localhost:8000/api/genres/8 HTTP/1.1
Accept: application/json
